name = "Old Man Mon"
author = "SonOfVader"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee21875500cdffd8223b2e5165dc39abf34138b5737d456ad59d953393e66f15"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
