name = "Old Man Mon"
author = "SonOfVader"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "490d6a86eb3f75ef64b1054b648de9733c3468d4b2263782dcc2d61dfc986847"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
