name = "Old Man Mon"
author = "SonOfVader"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd8221a8a0329c3e2ad461c0a6cb669d3d9105f935554b3eb714d1ff1f79ae44"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
